"use client"
import Link from 'next/link';
import './globals.css'
import { Inter } from 'next/font/google'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import { Button, Form } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] })
import mainPkg from '../../package.json';
import Image from 'next/image';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
                <title>BeeBeeSoft - IT Service and Software Development</title>
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                
                <link rel="icon" type="image/png" href="/img/favicon.png"/>
                <meta charSet="UTF-8"/>
                <meta name="description" content="BeeBeeSoft Support your bussiness make easier with Technology."/>
                <meta name="keywords" content="software development, beebeesoft"/>
                <meta name="author" content="BeeBeesoft Dev."></meta>
      </head>
      <body className={inter.className}>
        <Navbar fixed="top" bg="light" data-bs-theme="light" className="navbar navbar-expand-lg navbar-light bg-light bg-white shadow-sm">
          <Container>
            <Navbar.Brand href="/">
            <Image src="/img/logo/logo-name.png" width={100} height={50} alt="Logo Beebeesoft" />
            </Navbar.Brand>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
              <Nav className="me-auto">
                <Nav.Link href="/">Home</Nav.Link>
                {/* <Nav.Link href="#link">Link</Nav.Link>
                <NavDropdown title="Dropdown" id="basic-nav-dropdown">
                  <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.2">
                    Another action
                  </NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                  <NavDropdown.Divider />
                  <NavDropdown.Item href="#action/3.4">
                    Separated link
                  </NavDropdown.Item>
                </NavDropdown> */}
              </Nav>
              <Form className="d-flex">
              <Link href="/pricing/development">
                <Button variant="outline-success">Pricing</Button>
              </Link>
              </Form>
            </Navbar.Collapse>
          </Container>
        </Navbar>
        <div className='bgWhite'>
        <br /><br /><br />
        {children}

        </div>
        <div>
            <main className="py-4 frame">
            <div className="container">
                <div className="row" >
                    <div className="col-md-6">
                        
                        <h3>Hubungi Kami</h3>
                        <p><a href="https://api.whatsapp.com/send?phone=6285171064406&text=info" target="blank">
                            <i className="fab fa-whatsapp-square"></i> 0851 7106 4406
                        </a></p>
                        <p><a href="#">
                            <i className="fas fa-envelope-square"></i> admin@beebeesoft.com
                        </a></p>
                        <p><a href="https://www.instagram.com/beebeesoft.official/" target="blank">
                            <i className="fab fa-instagram"></i> BeeBeeSoft Official
                        </a></p>
                    </div>
                    <div className="col-md-6 text-end">
                        <h3>Alamat Kami</h3>
                        <p className="text-right">Perum Panorama Asri Jl. Sumbawa No. 27</p>
                        <p className="text-right">Kec.Sukahaji Kab.Majalengka </p>
                        <p className="text-right">Jawa Barat </p>
                        
                    </div>
                </div>
            </div>
            <p className="text-center">Copyright &copy; <Link href="/" >BeeBeeSoft</Link></p>
            <p className="text-center">Version { mainPkg.version }</p>
            </main>
            
        </div>
        </body>
    </html>
  )
}
